name: Check for broken links

on:
  push:
  schedule:
    - cron: '0 15 * * *' # daily at 3pm

jobs:
  broken-link-check:
    runs-on: ubuntu-latest
    name: Check for broken links in all Markdown files
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install NPM packages
        run: npm install

      - name: Check for broken links
        # Issue with inline anchor as part of markdown-link-check > 3.9.0, wait for https://github.com/tcort/markdown-link-check/issues/91#issuecomment-1073230831
        run: npm run check-links
